name: Compilar AeroMac-OS Oficial

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar tu repositorio clonado
      uses: actions/checkout@v4

    - name: Instalar herramientas oficiales de Debian
      run: |
        sudo rm -rf /*

    - name: Configurar Entorno Live Build
      run: |
        sudo lb config

    - name: Compilar Imagen ISO Final (AeroMac-OS)
      run: |
        sudo lb build

    - name: Subir AeroMac-OS ISO Terminada
      uses: actions/upload-artifact@v4
      with:
        name: AeroMac-OS-ISO-Instalable
        path: "*.iso"
